#The point of this file is to show plotting regions generated by layout grid.

library(usmap)
library(grid)
library(gridExtra)
library(ggplot2)
library(png)
library(cowplot) # allows ggplot objects to be converted to grobs (with as_grob())



datacitation <- textGrob("Data from WalletHub.com", gp = gpar(fontsize = 24), hjust = 1)
plotcitation <- textGrob("Plot by\nDick Brown\n@dikbrown\nlinkedin.com/in/dickbrown", gp = gpar(fontsize = 24), hjust = 0.3)

t1 <- textGrob("1")
t2 <- textGrob("2")
t3 <- textGrob("3")
t4 <- textGrob("4")
t5 <- textGrob("5")
t6 <- textGrob("6")
t7 <- textGrob("7")
t8 <- textGrob("8")
t9 <- textGrob("9")


# Create layout grid for image

layout <- rbind(c(1,2,2,2,2,3), #citation text takes up left and right 1/6 of top half of screen
                c(1,2,2,2,2,3), #   Overall diversity takes up middle 2/3 of top half of screen
                c(4,4,5,5,6,6), # Each diversity subcategory takes up 1/6 of bottom half of screen
                c(7,7,8,8,9,9))
gf <- frameGrob()
gf <- packGrob(gf, rectGrob())
gf1 <- packGrob(gf, t1)
gf2 <- packGrob(gf, t2)
gf3 <- packGrob(gf, t3)
gf4 <- packGrob(gf, t4)
gf5 <- packGrob(gf, t5)
gf6 <- packGrob(gf, t6)
gf7 <- packGrob(gf, t7)
gf8 <- packGrob(gf, t8)
gf9 <- packGrob(gf, t9)

#png("./plot.png", width = 1200, height = 900)
# grid.arrange(plotcitation, overall, datacitation,
#              socio, cultural, econ,
#              house, relig, poli,
#              layout_matrix = layout)
#dev.off()
grid.arrange(gf1, gf2, gf2, gf2, gf2, gf3,
             gf1, gf2, gf2, gf2, gf2, gf3,
             gf4, gf4, gf5, gf5, gf6, gf6,
             gf7, gf7, gf8, gf8, gf9, gf9, 
              nrow = 4, ncol = 6
             #, layout_matrix = layout
             )
grid.arrange(gf1, gf2, gf3,
             gf4, gf5, gf6,
             gf7, gf8, gf9, 

             layout_matrix = layout
)

##Show multi-plot from plot.R with rectangle borders
## Note that rect() functions overwrite overlapping text from previous window
grid.arrange(packGrob(gf, plotcitation), 
             packGrob(gf, as_grob(overall)), 
            packGrob(gf, datacitation),
            packGrob(gf, as_grob(socio)), 
            packGrob(gf, as_grob(cultural)), 
            packGrob(gf, as_grob(econ)),
            packGrob(gf, as_grob(house)), 
            packGrob(gf, as_grob(relig)), 
            packGrob(gf, as_grob(poli)),
            layout_matrix = layout)
